name: 'Setup Python + uv environment'
description: 'Setup Python + uv environment'

inputs:
  python-version:
    required: false
    description: 'Python version'
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: 'latest'

    - name: Install Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Synchronize dependencies
      run: uv sync
      shell: bash
